/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Room.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF("models/Room.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.729, -0.003, 0.525]} rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[0.761, 0.57, -0.158]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[-1.398, 10.973, 0]} scale={[33.609, 0.491, 18.465]}>
            <mesh
              geometry={nodes.pCube1_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, 0, 0.095]}
              scale={[1, 0.303, 1]}
            />
          </group>
          <group
            position={[-8.19, 28.428, -4.342]}
            scale={[10.961, 2.918, 0.312]}
          >
            <mesh
              geometry={nodes.pCube14_Desk1_0.geometry}
              material={materials.Desk1}
            />
            <mesh
              geometry={nodes.pCube14_Screen1_0.geometry}
              material={materials.Screen1}
            />
          </group>
          <group
            position={[-14.654, 12.086, 5.692]}
            rotation={[-Math.PI / 2, 0, 1.167]}
            scale={[3.384, 3.264, 2.281]}
          >
            <mesh
              geometry={nodes.pCube191_Screen1_0.geometry}
              material={materials.Screen1}
              position={[0, 0, -0.272]}
            />
          </group>
          <group
            position={[13.877, 4.477, -6.807]}
            rotation={[0, 1.571, 0]}
            scale={[0.998, 9.94, 1.73]}
          >
            <mesh
              geometry={nodes.pCube206_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, 0.165, -0.601]}
              scale={[1, 1.179, 1]}
            />
          </group>
          <group
            position={[-16.757, 4.477, -7.836]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[0.998, 9.94, 1.73]}
          >
            <mesh
              geometry={nodes.pCube207_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, 0.145, 0]}
              scale={[1, 1.2, 1]}
            />
          </group>
          <group
            position={[-16.757, 4.477, 5.164]}
            rotation={[0, -1.571, 0]}
            scale={[0.998, 9.94, 1.73]}
          >
            <mesh
              geometry={nodes.pCube208_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, 0.14, 0]}
              scale={[1, 1.24, 1]}
            />
          </group>
          <group
            position={[13.877, 4.477, 5.971]}
            rotation={[0, 1.571, 0]}
            scale={[0.998, 9.94, 1.73]}
          >
            <mesh
              geometry={nodes.pCube232_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, 0.14, 0]}
              scale={[1, 1.252, 1]}
            />
          </group>
          <group position={[-1.587, 0, -6.918]} rotation={[0, 0.698, 0]}>
            <mesh
              geometry={nodes.pCube266_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[-0.917, -0.102, -4.119]} rotation={[0, 0.414, 0]}>
            <mesh
              geometry={nodes.pCube267_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[-4.243, -0.102, -2.091]} rotation={[0, -0.318, 0]}>
            <mesh
              geometry={nodes.pCube268_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[1.857, 0, 0.373]}>
            <mesh
              geometry={nodes.pCube269_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[1.224, 0, 0.144]} rotation={[0, -Math.PI / 6, 0]}>
            <mesh
              geometry={nodes.pCube270_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[19.358, 0, 11.684]} rotation={[0, -0.698, 0]}>
            <mesh
              geometry={nodes.pCube271_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[27.738, 0.018, -17.717]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes.pCube277_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[2.835, 0, -0.715]} rotation={[0, -0.265, 0]}>
            <group position={[-2.212, -5.096, 0.241]} scale={[1, 1.441, 1]}>
              <mesh
                geometry={nodes.polySurface144_Desk1_0.geometry}
                material={materials.Desk1}
                position={[-0.703, 2.312, 1.868]}
                rotation={[0, 0.082, 0]}
                scale={0.765}
              />
            </group>
          </group>
          <group position={[0.598, 0, 0]}>
            <group position={[-2.38, -5.096, -0.12]} scale={[1, 1.441, 1]}>
              <mesh
                geometry={nodes.polySurface122_Desk1_0.geometry}
                material={materials.Desk1}
                position={[-0.579, 2.952, 2.128]}
                scale={[0.92, 0.722, 0.878]}
              />
            </group>
          </group>
          <group position={[-1.398, 0, 0]}>
            <mesh
              geometry={nodes.pCylinder34_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group
            position={[-0.641, 1.631, -3.09]}
            rotation={[1.548, 0, 0.482]}
            scale={0.168}
          >
            <mesh
              geometry={nodes.pCylinder49_Wires_0.geometry}
              material={materials.Wires}
              position={[-0.039, -0.074, 3.677]}
            />
          </group>
          <group position={[-2.969, 1.893, -17.789]}>
            <mesh
              geometry={nodes.polySurface13_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[-2.198, -5.155, -0.346]} scale={[1, 1.441, 1]}>
            <mesh
              geometry={nodes.polySurface143_Desk1_0.geometry}
              material={materials.Desk1}
              position={[-0.448, 2.321, 1.626]}
              rotation={[0, 0.082, 0]}
              scale={0.765}
            />
          </group>
          <group position={[15.784, -3.909, 6.182]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes.polySurface145_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
            <mesh
              geometry={nodes.polySurface145_Screen1_0.geometry}
              material={materials.Screen1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[-17.439, -15.069, 3.027]} rotation={[0, 1.338, 0]}>
            <mesh
              geometry={nodes.polySurface146_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
            <mesh
              geometry={nodes.polySurface146_Screen1_0.geometry}
              material={materials.Screen1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[3.164, 1.893, -17.84]}>
            <mesh
              geometry={nodes.polySurface148_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[-10.741, -0.068, -18.049]}>
            <mesh
              geometry={nodes.polySurface17_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <group position={[-2.38, -5.155, -0.12]} scale={[1, 1.441, 1]}>
            <mesh
              geometry={nodes.polySurface35_Desk1_0.geometry}
              material={materials.Desk1}
              position={[-0.531, 2.963, 2.128]}
              scale={[0.92, 0.722, 0.878]}
            />
          </group>
          <group position={[-0.756, 0, -0.487]}>
            <mesh
              geometry={nodes.polySurface7_Desk1_0.geometry}
              material={materials.Desk1}
              position={[0, -0.619, 0]}
            />
          </group>
          <mesh
            geometry={nodes.pCube17_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-5.548, 18.085, -5.899]}
            scale={[12.645, 0.324, 6.567]}
          />
          <mesh
            geometry={nodes.pCube209_Desk1_0.geometry}
            material={materials.Desk1}
            position={[17.678, 8.106, 11.81]}
            scale={[0.687, 12.45, 1.19]}
          />
          <mesh
            geometry={nodes.pCube210_Desk1_0.geometry}
            material={materials.Desk1}
            position={[27.843, 8.106, 11.81]}
            rotation={[0, -1.571, 0]}
            scale={[0.687, 12.45, 1.19]}
          />
          <mesh
            geometry={nodes.pCube211_Desk1_0.geometry}
            material={materials.Desk1}
            position={[27.843, 8.106, -0.693]}
            rotation={[0, 1.571, 0]}
            scale={[0.687, 12.45, 1.19]}
          />
          <mesh
            geometry={nodes.pCube212_Desk1_0.geometry}
            material={materials.Desk1}
            position={[17.678, 8.106, -0.693]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[0.687, 12.45, 1.19]}
          />
          <mesh
            geometry={nodes.pCube213_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-5.548, 21.996, -5.899]}
            scale={[12.645, 0.324, 6.567]}
          />
          <mesh
            geometry={nodes.pCube214_Desk1_0.geometry}
            material={materials.Desk1}
            position={[7.094, 18.085, -5.899]}
            scale={[12.645, 0.324, 6.567]}
          />
          <mesh
            geometry={nodes.pCube215_Desk1_0.geometry}
            material={materials.Desk1}
            position={[7.094, 25.369, -5.899]}
            scale={[12.645, 0.324, 6.567]}
          />
          <mesh
            geometry={nodes.pCube216_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-22.46, 13.284, -5.899]}
            scale={[12.645, 0.324, 6.567]}
          />
          <mesh
            geometry={nodes.pCube217_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-22.46, 20.536, -5.899]}
            scale={[12.645, 0.324, 6.567]}
          />
          <mesh
            geometry={nodes.pCube223_Desk1_0.geometry}
            material={materials.Desk1}
            position={[29.9, 12.664, 5.069]}
            scale={[26.817, 0.687, 13.927]}
          />
          <mesh
            geometry={nodes.pCube227_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-19.029, 0.619, 5.838]}
            rotation={[0, 1.571, 0]}
            scale={[24.967, 0.627, 12.702]}
          />
          <mesh
            geometry={nodes.pCube228_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-25.374, 2.479, -2.84]}
            scale={[25.355, 0.651, 12.899]}
          />
          <mesh
            geometry={nodes.pCube230_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-21.901, 5.427, 3.923]}
            scale={[6.142, 10.259, 10.321]}
          />
          <mesh
            geometry={nodes.pCube233_Desk1_0.geometry}
            material={materials.Desk1}
            position={[20.038, 2.479, 4.386]}
            scale={[25.355, 0.651, 12.899]}
          />
          <mesh
            geometry={nodes.pCube234_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-8.143, 22.344, -6.061]}
            scale={[5.005, 0.415, 2.246]}
          />
          <mesh
            geometry={nodes.pCube238_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-9.946, 28.42, -6.096]}
            scale={[0.74, 0.488, 2.42]}
          />
          <mesh
            geometry={nodes.pCube239_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-6.313, 22.367, -6.096]}
            scale={[0.74, 0.488, 2.42]}
          />
          <mesh
            geometry={nodes.pCube240_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-6.313, 28.42, -6.096]}
            scale={[0.74, 0.488, 2.42]}
          />
          <mesh
            geometry={nodes.pCube245_Screen1_0.geometry}
            material={materials.Screen1}
            position={[-8.224, 21.629, -2.772]}
            rotation={[0.406, 0, 0]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube246_Screen1_0.geometry}
            material={materials.Screen1}
            position={[18.268, 18.968, 5.628]}
            rotation={[0, -1.571, 0]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube247_Screen1_0.geometry}
            material={materials.Screen1}
            position={[-14.453, 19.224, -1.484]}
            rotation={[0.387, 0.661, -0.245]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube248_Screen1_0.geometry}
            material={materials.Screen1}
            position={[-1.657, 22.652, -2.796]}
            rotation={[0.237, 0, 0]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube249_Screen1_0.geometry}
            material={materials.Screen1}
            position={[10.931, 20.925, -0.755]}
            rotation={[0.34, -0.669, 0.216]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube250_Screen1_0.geometry}
            material={materials.Screen1}
            position={[-6.572, 15.925, -2.207]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube251_Screen1_0.geometry}
            material={materials.Screen1}
            position={[4.367, 15.925, -0.954]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube254_Screen1_0.geometry}
            material={materials.Screen1}
            position={[10.959, 11.594, 6.681]}
            rotation={[-Math.PI / 2, 0, -1.21]}
            scale={[3.384, 3.264, 2.281]}
          />
          <mesh
            geometry={nodes.pCube255_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-21.046, 15.643, -4.936]}
            scale={[1.953, 4.437, 3.1]}
          />
          <mesh
            geometry={nodes.pCube256_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-21.91, 5.589, 5.427]}
            scale={[4.711, 9.802, 6.849]}
          />
          <mesh
            geometry={nodes.pCube257_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-1.088, 14.187, -4.936]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube259_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-25.749, 17.554, -5.702]}
            scale={[3.604, 8.189, 5.722]}
          />
          <mesh
            geometry={nodes.pCube260_Computer1_0.geometry}
            material={materials.Computer1}
            position={[24.659, 14.63, 10.319]}
            rotation={[0, -1.571, 0]}
            scale={[3.387, 3.267, 2.283]}
          />
          <mesh
            geometry={nodes.pCube261_Computer1_0.geometry}
            material={materials.Computer1}
            position={[19.323, 16.143, 4.75]}
            rotation={[0, -1.571, 0]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube262_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-9.134, 14.128, -6.682]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube263_Computer1_0.geometry}
            material={materials.Computer1}
            position={[20.647, 17.525, -5.931]}
            scale={[3.604, 8.189, 5.722]}
          />
          <mesh
            geometry={nodes.pCube264_Computer1_0.geometry}
            material={materials.Computer1}
            position={[19.253, 15.224, 10.937]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1.953, 4.437, 3.1]}
          />
          <mesh
            geometry={nodes.pCube265_Computer1_0.geometry}
            material={materials.Computer1}
            position={[22.046, 7.251, 8.197]}
            rotation={[0, -1.571, 0]}
            scale={[4.294, 8.933, 6.242]}
          />
          <mesh
            geometry={nodes.pCube273_Desk1_0.geometry}
            material={materials.Desk1}
            position={[19.532, 2.479, -2.84]}
            scale={[25.355, 0.651, 12.899]}
          />
          <mesh
            geometry={nodes.pCube274_Desk1_0.geometry}
            material={materials.Desk1}
            position={[22.447, 13.284, -5.899]}
            scale={[12.645, 0.324, 6.567]}
          />
          <mesh
            geometry={nodes.pCube28_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-9.946, 22.367, -6.096]}
            scale={[0.74, 0.488, 2.42]}
          />
          <mesh
            geometry={nodes.pCube280_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-1.626, 21.38, -6.68]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube281_Computer1_0.geometry}
            material={materials.Computer1}
            position={[1.927, 21.38, -6.68]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube283_Computer1_0.geometry}
            material={materials.Computer1}
            position={[22.046, 7.251, 3.358]}
            rotation={[0, -1.571, 0]}
            scale={[4.294, 8.933, 6.242]}
          />
          <mesh
            geometry={nodes.pCube284_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-12.099, 3.57, -1.551]}
            scale={[4.064, 8.455, 5.908]}
          />
          <mesh
            geometry={nodes.pCube285_Computer1_0.geometry}
            material={materials.Computer1}
            position={[7.58, 3.65, -1.868]}
            scale={[4.092, 8.514, 5.949]}
          />
          <mesh
            geometry={nodes.pCube286_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-7.499, 3.57, -1.816]}
            scale={[4.064, 8.455, 5.908]}
          />
          <mesh
            geometry={nodes.pCube287_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-25.369, 7.069, -5.713]}
            scale={[4.064, 8.455, 5.908]}
          />
          <mesh
            geometry={nodes.pCube288_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-7.958, 21.421, -5.556]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube290_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-16.452, 14.178, -5.879]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube291_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-13.375, 14.107, -6.795]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube292_Computer1_0.geometry}
            material={materials.Computer1}
            position={[20.617, 23.646, -5.921]}
            scale={[3.604, 8.189, 5.722]}
          />
          <mesh
            geometry={nodes.pCube293_Computer1_0.geometry}
            material={materials.Computer1}
            position={[19.351, 17.502, 4.786]}
            rotation={[0, -1.571, 0]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube294_Computer1_0.geometry}
            material={materials.Computer1}
            position={[24.727, 17.047, 10.267]}
            rotation={[0, -1.571, 0]}
            scale={[3.387, 3.267, 2.283]}
          />
          <mesh
            geometry={nodes.pCube295_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-2.551, 5.423, -10.223]}
            rotation={[0, 0.698, 0]}
          />
          <mesh
            geometry={nodes.pCube297_Screen1_0.geometry}
            material={materials.Screen1}
            position={[-16.142, 23.716, -3.564]}
            rotation={[0.388, 0.652, -0.231]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube298_Screen1_0.geometry}
            material={materials.Screen1}
            position={[5.953, 23.108, -2.193]}
            rotation={[0.236, -0.152, 0.033]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube299_Computer1_0.geometry}
            material={materials.Computer1}
            position={[21.227, 7.069, -5.713]}
            scale={[4.064, 8.455, 5.908]}
          />
          <mesh
            geometry={nodes.pCube300_Computer1_0.geometry}
            material={materials.Computer1}
            position={[13.036, 14.107, -5.659]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube301_Computer1_0.geometry}
            material={materials.Computer1}
            position={[10.175, 14.107, -5.693]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube302_Computer1_0.geometry}
            material={materials.Computer1}
            position={[13.036, 20.124, -5.659]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube303_Computer1_0.geometry}
            material={materials.Computer1}
            position={[10.175, 20.124, -5.693]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube304_Computer1_0.geometry}
            material={materials.Computer1}
            position={[10.958, 26.575, -6.059]}
            scale={[3.138, 7.131, 4.982]}
          />
          <mesh
            geometry={nodes.pCube305_Computer1_0.geometry}
            material={materials.Computer1}
            position={[20.626, 20.589, -5.9]}
            scale={[3.604, 8.189, 5.722]}
          />
          <mesh
            geometry={nodes.pCube306_Screen1_0.geometry}
            material={materials.Screen1}
            position={[4.586, 27.623, -4.879]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube307_Computer1_0.geometry}
            material={materials.Computer1}
            position={[4.798, 14.148, -5.022]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube308_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-6.482, 13.22, -6.358]}
            scale={[1.953, 4.437, 3.1]}
          />
          <mesh
            geometry={nodes.pCube309_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-20.658, 24.777, -4.415]}
            scale={[3.387, 3.267, 2.283]}
          />
          <mesh
            geometry={nodes.pCube310_Computer1_0.geometry}
            material={materials.Computer1}
            position={[0.043, 2.529, -5.098]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube311_Computer1_0.geometry}
            material={materials.Computer1}
            position={[3.219, 2.515, -4.768]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCube32_Screen1_0.geometry}
            material={materials.Screen1}
            position={[-12.423, 13.028, 1.172]}
            rotation={[0, 0.808, 0]}
            scale={[4.261, 4.11, 2.872]}
          />
          <mesh
            geometry={nodes.pCube36_Computer1_0.geometry}
            material={materials.Computer1}
            position={[-20.657, 22.356, -4.396]}
            scale={[3.387, 3.267, 2.283]}
          />
          <mesh
            geometry={nodes.pCube42_Computer1_0.geometry}
            material={materials.Computer1}
            position={[5.472, 21.38, -6.68]}
            scale={[2.766, 6.286, 4.392]}
          />
          <mesh
            geometry={nodes.pCylinder12_Screen1_0.geometry}
            material={materials.Screen1}
            position={[13.73, 13.745, 4.508]}
            scale={[0.344, 2.481, 0.344]}
          />
          <mesh
            geometry={nodes.pCylinder38_Wires_0.geometry}
            material={materials.Wires}
            position={[-8.868, 18.646, -3.565]}
            rotation={[1.548, 0, 0]}
            scale={0.145}
          />
          <mesh
            geometry={nodes.pCylinder41_Wires_0.geometry}
            material={materials.Wires}
            position={[-25.55, 24.863, -3.624]}
            rotation={[1.548, 0, 0]}
            scale={0.145}
          />
          <mesh
            geometry={nodes.pCylinder42_Wires_0.geometry}
            material={materials.Wires}
            position={[-24.561, 21.265, -3.39]}
            rotation={[1.548, 0, 0]}
            scale={0.145}
          />
          <mesh
            geometry={nodes.pCylinder45_Wires_0.geometry}
            material={materials.Wires}
            position={[15.114, 0.443, 4.568]}
            rotation={[1.548, 0, 1.778]}
            scale={0.206}
          />
          <mesh
            geometry={nodes.pCylinder46_Wires_0.geometry}
            material={materials.Wires}
            position={[2.623, 21.771, -4.615]}
            rotation={[1.548, 0, 0]}
            scale={0.197}
          />
          <mesh
            geometry={nodes.pCylinder47_Wires_0.geometry}
            material={materials.Wires}
            position={[19.399, 21.404, -3.184]}
            rotation={[1.548, 0, 0]}
            scale={0.168}
          />
          <mesh
            geometry={nodes.pCylinder48_Wires_0.geometry}
            material={materials.Wires}
            position={[-16.677, 15.844, -3.924]}
            rotation={[1.548, 0, 0]}
            scale={0.168}
          />
          <mesh
            geometry={nodes.pCylinder50_Wires_0.geometry}
            material={materials.Wires}
            position={[12.414, 23.42, -3.804]}
            rotation={[1.548, 0, 0]}
            scale={0.145}
          />
          <mesh
            geometry={nodes.pCylinder51_Wires_0.geometry}
            material={materials.Wires}
            position={[5.592, 21.766, -4.726]}
            rotation={[1.548, 0, 0]}
            scale={0.168}
          />
          <mesh
            geometry={nodes.pCylinder52_Wires_0.geometry}
            material={materials.Wires}
            position={[0.157, 4.16, -3.142]}
            rotation={[1.548, 0, 0]}
            scale={0.168}
          />
          <mesh
            geometry={nodes.pCylinder53_Wires_0.geometry}
            material={materials.Wires}
            position={[-21.513, 21.555, -3.574]}
            rotation={[1.548, 0, 0]}
            scale={0.168}
          />
          <mesh
            geometry={nodes.pCylinder54_Wires_0.geometry}
            material={materials.Wires}
            position={[19.859, 21.405, -3.325]}
            rotation={[1.548, 0, 0]}
            scale={0.168}
          />
          <mesh
            geometry={nodes.polySurface20_Desk1_0.geometry}
            material={materials.Desk1}
            position={[0, -0.619, 0]}
          />
          <mesh
            geometry={nodes.polySurface20_Screen1_0.geometry}
            material={materials.Screen1}
            position={[0, -0.619, 0]}
          />
          <mesh
            geometry={nodes.pTorus100_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-35.693, 18.62, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus101_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-35.693, 15.25, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus102_Desk1_0.geometry}
            material={materials.Desk1}
            position={[9.217, 7.992, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus103_Desk1_0.geometry}
            material={materials.Desk1}
            position={[9.219, 11.365, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus104_Desk1_0.geometry}
            material={materials.Desk1}
            position={[0.255, 11.365, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus105_Desk1_0.geometry}
            material={materials.Desk1}
            position={[0.253, 7.992, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus106_Desk1_0.geometry}
            material={materials.Desk1}
            position={[9.213, 18.62, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus107_Desk1_0.geometry}
            material={materials.Desk1}
            position={[9.213, 15.25, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus108_Desk1_0.geometry}
            material={materials.Desk1}
            position={[0.259, 18.62, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus109_Desk1_0.geometry}
            material={materials.Desk1}
            position={[0.259, 15.25, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus32_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-27.706, 12.799, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus79_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-44.653, 7.992, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus80_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-27.706, 16.17, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus81_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-21.375, 16.17, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus82_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-21.375, 12.799, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus83_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-20.161, 16.17, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus84_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-20.161, 12.799, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus85_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-8.725, 16.17, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus86_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-8.725, 12.799, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus87_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-20.161, 23.461, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus88_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-20.161, 20.09, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus89_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-8.725, 20.09, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus90_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-8.725, 23.461, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus92_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-21.375, 20.09, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus94_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-27.706, 20.09, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus95_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-44.651, 11.365, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus96_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-35.688, 11.365, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus97_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-35.689, 7.992, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus98_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-44.648, 18.62, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
          <mesh
            geometry={nodes.pTorus99_Desk1_0.geometry}
            material={materials.Desk1}
            position={[-44.648, 15.25, -5.784]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.884, 0.765, 0.884]}
          />
        </group>
      </group>
      <group
        position={[-0.001, -0.098, 0.108]}
        rotation={[Math.PI / 2, 0, -1.549]}
        scale={0.002}
      >
        <group scale={100}>
          <group scale={0.01}>
            <group position={[8.001, 0, 18.595]}>
              <mesh
                geometry={nodes.__3_0.geometry}
                material={materials.material_2}
                position={[0.018, -0.012, 12.656]}
              />
            </group>
            <group position={[8.001, 0, 3.934]}>
              <mesh
                geometry={nodes.__4_0.geometry}
                material={materials.material_3}
                position={[0, 0, 0.752]}
                scale={[1, 1, 1.802]}
              />
            </group>
            <mesh
              geometry={nodes.__1_0.geometry}
              material={materials.material}
              position={[-12.13, 0, -10.551]}
              rotation={[0, 0.118, 0]}
            />
            <mesh
              geometry={nodes.__2_0.geometry}
              material={materials.material_1}
              position={[8.258, -0.014, -1.427]}
            />
            <mesh
              geometry={nodes.__5_0.geometry}
              material={materials.material_4}
              position={[-12.13, 0, -10.551]}
              rotation={[0, 0.118, 0]}
            />
            <mesh
              geometry={nodes.__6_0.geometry}
              material={materials.material_5}
              position={[-12.178, 8.018, -9.461]}
              rotation={[Math.PI / 2, 0, -0.328]}
            />
            <mesh
              geometry={nodes.__7_0.geometry}
              material={materials.material_6}
              position={[-12.178, 8.018, -9.461]}
              rotation={[Math.PI / 2, 0, -0.328]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.307, -0.161, -0.698]}
        rotation={[-Math.PI / 2, 0, -1.748]}
      >
        <group
          position={[0.784, 0.57, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            geometry={nodes.pCube191_Screen1_0001.geometry}
            material={materials["Screen1.004"]}
            position={[-14.654, 11.467, 5.692]}
            rotation={[-Math.PI / 2, 0, 1.167]}
            scale={[3.384, 3.264, 2.281]}
          />
        </group>
      </group>
      <group
        position={[-2.956, -0.028, 1.218]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0028.geometry}
              material={materials["Ground1.269"]}
              position={[-0.248, 0, -0.029]}
              scale={[0.651, 0.378, 0.464]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-6.72, -0.008, 6.01]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[11.886, 14.083, 11.249]}
      >
        <group
          position={[0.782, 0.57, -0.014]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0040.geometry}
              material={materials["Ground1.281"]}
              position={[-0.266, 0, -0.085]}
              scale={[0.431, 0.431, 0.446]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-3.032, -0.033, 9.42]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[11.886, 14.083, 11.249]}
      >
        <group
          position={[0.784, 0.57, -0.012]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0042.geometry}
              material={materials["Ground1.283"]}
              position={[-0.265, 0, -0.06]}
              scale={[0.418, 0.378, 0.378]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-1.62, -0.028, 2.156]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0001.geometry}
              material={materials["Ground1.284"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.793, -0.028, 2.156]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0002.geometry}
              material={materials["Ground1.285"]}
              position={[-0.394, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[0.015, -0.028, 2.156]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0003.geometry}
              material={materials["Ground1.286"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[0.015, -0.028, 2.902]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0005.geometry}
              material={materials["Ground1.287"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[0.015, -0.028, 3.614]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0006.geometry}
              material={materials["Ground1.288"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[0.015, -0.028, 4.337]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0007.geometry}
              material={materials["Ground1.289"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[0.015, -0.028, 5.122]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0008.geometry}
              material={materials["Ground1.290"]}
              position={[-0.39, 0, -0.565]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.791, -0.028, 5.122]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0009.geometry}
              material={materials["Ground1.291"]}
              position={[-0.39, 0, -0.565]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.791, -0.028, 4.337]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0010.geometry}
              material={materials["Ground1.292"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.791, -0.028, 3.614]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0011.geometry}
              material={materials["Ground1.293"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.791, -0.028, 2.902]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0012.geometry}
              material={materials["Ground1.294"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-1.608, -0.028, 2.902]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0013.geometry}
              material={materials["Ground1.295"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-1.608, -0.028, 3.614]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0014.geometry}
              material={materials["Ground1.296"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-1.608, -0.028, 4.337]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0015.geometry}
              material={materials["Ground1.297"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-1.608, -0.028, 5.122]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0016.geometry}
              material={materials["Ground1.298"]}
              position={[-0.39, 0, -0.565]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-2.404, -0.028, 5.122]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0017.geometry}
              material={materials["Ground1.299"]}
              position={[-0.39, 0, -0.565]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-2.404, -0.028, 4.337]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0018.geometry}
              material={materials["Ground1.300"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-2.404, -0.028, 3.614]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0019.geometry}
              material={materials["Ground1.301"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-2.404, -0.028, 2.902]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0020.geometry}
              material={materials["Ground1.302"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-3.182, -0.028, 2.902]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0021.geometry}
              material={materials["Ground1.303"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-3.182, -0.028, 3.614]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0022.geometry}
              material={materials["Ground1.304"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-3.182, -0.028, 4.337]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0023.geometry}
              material={materials["Ground1.305"]}
              position={[-0.39, 0, -0.552]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-3.182, -0.028, 5.122]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.722}
      >
        <group
          position={[0.784, 0.57, -0.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group position={[0.773, 0, 0.516]} scale={[83.682, 64.541, 64.541]}>
            <mesh
              geometry={nodes.pPlane1_Ground1_0024.geometry}
              material={materials["Ground1.306"]}
              position={[-0.39, 0, -0.565]}
              scale={[0.362, 0.362, 0.444]}
            />
          </group>
        </group>
      </group>
      <group
        position={[0.486, -0.164, 1.071]}
        rotation={[-Math.PI / 2, 0, 1.556]}
      >
        <group
          position={[0.761, 0.57, -0.158]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group
            position={[24.727, 17.047, 10.267]}
            rotation={[0, -1.571, 0]}
            scale={[3.387, 3.267, 2.283]}
          >
            <mesh
              geometry={nodes.pCube294_Computer1_0001.geometry}
              material={materials["Computer1.002"]}
              position={[-0.019, 0.108, -1.916]}
              scale={[1, 0.78, 1]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/Room.gltf");
